### PR TITLE
Automatically pass generated rejections to ProtoData

### PR DESCRIPTION
**Pull request by dmdashenkov**
In this PR we make the `mc-java` plugin pass generated rejections as well as basic generated message classes to ProtoData.

This is possible with the new ProtoData v0.2.11. 

This change is contingent on [this ProtoData PR](https://github.com/SpineEventEngine/ProtoData/pull/78) and [this validation PR](https://github.com/SpineEventEngine/validation/pull/40).

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@armiol, PTAL.

**Review by armiol — CHANGES_REQUESTED** [review]
As discussed, please use the newly introduced API to allow proper processing of generated rejections.

**Comment by dmdashenkov** [comment]
@armiol, PTAL.

**Review by armiol — APPROVED** [review]
@dmdashenkov LGTM.

**Pull request merged**
